- hosts: localhost
  become: true
  vars_files: "./vars.yml"
  tasks:
    - import_tasks: "./tasks/packages.yml"
      tags:
        - packages
    - import_tasks: "./tasks/users.yml"
      tags:
        - users
    - import_tasks: "./tasks/env.yml"
      tags:
        - env
  roles:
    - role: gantsign.visual-studio-code
      users:
        - username: will
          visual_studio_code_extensions:
            - vscoss.vscode-ansible
            - dcasella.i3