- hosts: localhost
  become: true
  vars_files: "./vars.yml"
  tasks:
    - import_tasks: "./tasks/packages.yml"
      tags:
        - packages
    - import_tasks: "./tasks/users.yml"
      tags:
        - users
    - import_tasks: "./tasks/env.yml"
      tags:
        - env
  roles:
    - role: gantsign.visual-studio-code
      users:
        - username: will
          visual_studio_code_extensions:
            - vscoss.vscode-ansible
            - dcasella.i3
            # https://pmateusz.github.io/latex/2018/01/30/vs-code-latex-editor.html
            - James-Yu.latex-workshop
            - streetsidesoftware.code-spell-checker
            - tomoki1207.pdf
            - dbaeumer.vscode-eslint
            - arcticicestudio.nord-visual-studio-code
            - ms-python.python
            - naumovs.color-highlight
            - coolbear.systemd-unit-file
    - role: geerlingguy.nodejs
      nodejs_version: "11.x"
      nodejs_npm_global_packages:
        - "@bitwarden/cli"
        - "tsc"