- name: "Apt packages"
  include_tasks: "apt.yml"
  when: distro == "debian"

- name: "Pacman packages"
  include_tasks: "pacman.yml"
  when: distro == "pacman"

- name: Install snaps
  command: snap install "{{ item }}" --classic
  loop: "{{ snaps }}"
  when: snaps is defined

- name: Install flatpaks
  flatpak:
    name: "{{ item }}"
  loop: "{{ paks }}"
  when: paks is defined
