- name: Update cache
  pacman:
    update_cache: yes
  become: yes
  become_method: sudo

- name: Install standard packages
  pacman:
    name: "{{ packages }}"
    state: latest
  when: packages is defined
  become: yes
  become_method: sudo