- name: Add apt keys
  loop: "{{ apt_keys }}"
  apt_key: 
    url: "{{ item.url }}"
    keyring: "{{ item.keyring }}"
    id: "{{ item.id }}"

- name: Add apt repos
  loop: "{{ apt_repos }}"
  apt_repository: 
    repo: "{{ item }}"

- name: Add ppas
  apt_repository: 
    repo: "{{ item }}"
    state: present
  loop: "{{ apt_ppas }}"

- name: Install debs
  become: true
  apt:
    deb: "{{ item }}"
    state: present
  loop: "{{ debs }}"

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install standard packages
  become: true
  apt:
    name: "{{ packages }}"
    state: latest

- name: Install snaps
  command: snap install "{{ item }}" --classic
  loop: "{{ snaps }}"

- name: Install flatpaks
  flatpak:
    name: "{{ item }}"
  loop: "{{ paks }}"

- name: Install python packages
  pip:
    name: pygments
    executable: pip

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
