- name: Ensure groups exist
  group:
    name: docker
    state: present

- name: Set user opts
  user:
    name: will
    shell: /bin/zsh
    group: will
    groups: [adm, cdrom, sudo, dip, plugdev, lpadmin, sambashare, docker]