- name: Ensure ~/.zshrc is correct
  template:
    src: zshrc
    dest: /home/will/.zshrc
    owner: will
    group: will
- name: Ensure ~/.zprofile is correct
  template:
    src: zprofile.j2
    dest: /home/will/.zprofile
    owner: will
    group: will
- name: Ensure oh-my-zsh is correct
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: /home/will/.oh-my-zsh
  become: yes
  become_user: will