- name: Ensure ~/.config/sway exists
  file:
    path: /home/will/.config/sway
    owner: will
    group: will
    mode: u+rwx
    state: directory
- name: Ensure ~/.config/sway/config is up to date
  template: 
    src: sway.config.j2
    dest: /home/will/.config/sway/config
    owner: will
    group: will
    mode: u+rwx