- name: Create a directory if it does not exist
  file:
    path: /home/will/.config/systemd/user/
    state: directory
    owner: will
    group: will

- name: Install systemd service
  copy:
    src: ssh-agent.service.j2
    dest: /home/will/.config/systemd/user/ssh-agent.service
    owner: will
    group: will
    mode: u+r
